language: csharp
solution: PndTools.sln
matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003131
script:
  - dotnet restore
  - cd test/PndToolsTests
  - dotnet test