language: csharp
solution: PndTools.sln
matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      mono: none
      dotnet: 1.0.4
script:
  - dotnet restore
  - dotnet build
  - dotnet test test/**/*.csproj
