default_install_hook_types = ["pre-commit", "commit-msg"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "dotnet-format"
name = "dotnet format"
language = "system"
entry = "dotnet format --verify-no-changes --no-restore"
files = '\.(cs|csproj|props|editorconfig)$'
stages = ["pre-commit"]
pass_filenames = false

[[repos.hooks]]
id = "markdownlint"
name = "markdownlint"
language = "system"
entry = "npx markdownlint-cli2"
types = ["markdown"]
stages = ["pre-commit"]

[[repos.hooks]]
id = "commitlint"
name = "commitlint"
language = "system"
entry = "npx commitlint --edit"
stages = ["commit-msg"]
always_run = true
pass_filenames = false
